
services:
  django:
    build:
      context: .
    container_name: django_app
    command: daphne -b 0.0.0.0 -p 8000 taskmainder.asgi:application
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - .env
    restart: unless-stopped

  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  celery_worker:
    build:
      context: .
    container_name: celery_worker
    command: celery -A taskmainder worker --loglevel=info
    depends_on:
      - redis
      - django
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped

  celery_beat:
    build:
      context: .
    container_name: celery_beat
    command: celery -A taskmainder beat --loglevel=info
    depends_on:
      - redis
      - django
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped

volumes:
  static_volume:
  media_volume: